### ISSUE TITLE
backgrounds and some elements not drawn on GTK3.20,21,22

### ISSUE THREAD

**Issue by kilobyte** [originalseed/darkmint#2]
While the theme is awesome for anything that uses GTK2, on GTK3 it's mostly unusable: on many windows such as menus, popup dialogs, etc, the background is not drawn, displaying whatever junk was behind.  This tends to make text unreadable.

Also, menu borders/etc are missing.

GTK3 is notorious for breaking everything even in minor versions, requiring updates to programs and themes, and it just broke yours...

**Comment by kilobyte** [comment]
Actually GTK3.20 is broken, too.

I see you're on the issue in your other theme (https://github.com/originalseed/darkcold/issues/3), you probably want to test it for the new 3.22, available in Debian unstable and Fedora rawhide.

**Comment by originalseed** [comment]
Support added for 3.22
