### ISSUE TITLE
metacity metadata gives wrong names and authors

### ISSUE THREAD

**Issue by kilobyte** [originalseed/darkmint#4]
Metadata says:
 * metacity-theme-1.xml: name: DarkCold
 * metacity-theme-3.xml: name: Arc author/copyright: horst3180

You'd want to change that to DarkMint and you.

**Comment by originalseed** [comment]
I copied the file from Mint-X metacity theme. For some reason buy just adding a metacity v3 file to theme works again. So the author is not me.
